# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3dc93ab2f12bcfca8b210dec757e9062a08c5f2246b6bf26d6c029ea9db44b102bb4314413f597c5edac413dcbd23a8f72552e937140c2d92519beb1ee1f009

test:
  secret_key_base: cd97aaf351e926ad2293e15f2e8da3c30b44e8f68d181068d1acd4b5065f5ef6fd8eec147ca72b18b4b00f01ddb5b558112f25b030db2cce352c614bda6a6703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
